# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeuserreport',
            options={'verbose_name': '活跃用户', 'verbose_name_plural': '活跃用户'},
        ),
        migrations.AlterModelOptions(
            name='salereport',
            options={'verbose_name': '每天销售额', 'verbose_name_plural': '每天销售额'},
        ),
        migrations.AlterField(
            model_name='salereport',
            name='status_time',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
