# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20170913_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuserreport',
            name='status_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='status_time',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
